# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'w': 'session-save','o': 'open', 'q': 'quit', 'wq': 'quit --save',
            'today': 'open http://www.linuxtoday.com'}

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# customizations

c.url.searchengines = {'DEFAULT': 'https://duckduckgo.com/?q={}',
        'aw': 'https://wiki.archlinux.org/?search={}',
        'yt': 'https://www.youtube.com/results?search_query={}',
        'wikfr': 'https://fr.wikipedia.org/wiki/{}',
        'wikde': 'https://de.wikipedia.org/wiki/{}',
        'wiken': 'https://en.wikipedia.org/wiki/{}',
        'github': 'https://github.com/search?utf8=%E2%9C%93&q={}&type=',
        'g': 'https://encrypted.google.com/search?pws=0&suggon=0&safe=off&filter=0&num=30&q={}&tbs=li:1',
        'gi': 'https://encrypted.google.com/search?q={}&source=lnms&tbm=isch&sa=X'
        }
